name: Tests

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: rewriteReadme
        uses: deatil/some-work-actions@main
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          pattern: '<!-- issueTable -->'
          labels: 'pkg'
          state: 'all'

