name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
    contents: write
    packages: write

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: rewriteReadme
        uses: deatil/some-work-actions@main
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          pattern: '<!-- issueTable -->'
          labels: 'pkg'
          state: 'all'

